CRITICAL - 2022-02-15 05:08:28 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:08:35 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:08:47 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:02 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:02 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:11 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:14 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:17 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 05:09:51 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:09:52 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:09:59 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:10:37 --> syntax error, unexpected '(', expecting variable (T_VARIABLE)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:10:58 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:11:08 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:11:09 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 05:11:31 --> syntax error, unexpected 'helper' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 07:48:02 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:03 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:05 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:07 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:07 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:07 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:08 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:08 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:08 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:09 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:10 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:17 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 07:48:49 --> syntax error, unexpected ';', expecting ')'
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 08:31:33 --> syntax error, unexpected 'return' (T_RETURN)
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 08:31:39 --> syntax error, unexpected 'return' (T_RETURN)
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 08:31:41 --> syntax error, unexpected 'return' (T_RETURN)
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 08:31:54 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:32:19 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:32:32 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:32:42 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:32:58 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:33:36 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:33:46 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:33:54 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:34:12 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 08:59:46 --> syntax error, unexpected 'if' (T_IF)
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 08:59:51 --> syntax error, unexpected 'if' (T_IF)
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 09:00:22 --> Call to undefined function Config\add()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:00:23 --> Call to undefined function Config\add()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:00:32 --> Call to undefined function Config\get()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:00:33 --> Call to undefined function Config\get()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:00:55 --> Call to undefined function Config\get()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:01:13 --> Call to undefined function Config\add()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(706): require()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 09:01:51 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:02:07 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:02:22 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:02:33 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:02:44 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:04:19 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:05:17 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:05:26 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:05:39 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:05:47 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:05:56 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:06:03 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:06:21 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:06:28 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:06:38 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:06:47 --> Undefined property: CodeIgniter\CodeIgniter::$load
#0 D:\xammp\htdocs\ci4\app\Config\Routes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'D:\\xammp\\htdocs...', 36, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(781): CodeIgniter\CodeIgniter->Config\{closure}()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:07:04 --> syntax error, unexpected '}', expecting ';' or ','
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 09:07:07 --> syntax error, unexpected '}', expecting ';' or ','
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 09:07:08 --> syntax error, unexpected '}', expecting ';' or ','
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-02-15 09:07:24 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('registration')
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle('registration')
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 09:07:35 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:07:41 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:07:52 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:08:01 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:08:18 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:10:03 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:10:16 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:10:37 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:31:14 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 09:31:36 --> syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-15 09:36:56 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:36:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('fbk4f@kg7t.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'fbk4f@kg7t.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(36): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:38:51 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:38:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('udmn9@vzqn.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'udmn9@vzqn.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(36): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:40:05 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:40:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('tcynl@6so7.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'tcynl@6so7.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(32): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:46:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:46:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('o8ypy@lbol.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'o8ypy@lbol.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(33): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:49:05 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:49:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('o8ypy@lbol.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'o8ypy@lbol.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:49:30 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:49:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('o8ypy@lbol.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'o8ypy@lbol.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:51:55 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:51:55 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('aeihj@yvng.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'aeihj@yvng.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:52:48 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:52:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('aeihj@yvng.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'aeihj@yvng.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:53:34 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:53:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('aeihj@yvng.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'aeihj@yvng.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:54:32 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:54:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('2tu47@t29f.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', '2tu47@t29f.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:56:27 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:56:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('2tu47@t29f.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', '2tu47@t29f.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 09:56:45 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 09:56:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('jxtvb@agnv.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'jxtvb@agnv.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:03:19 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:03:19 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('jxtvb@agnv.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'jxtvb@agnv.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:03:56 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:03:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('muwjd@5wuo.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muwjd@5wuo.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:05:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:05:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('muwjd@5wuo.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muwjd@5wuo.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 10:05:22 --> Use of undefined constant d - assumed 'd' (this will throw an Error in a future version of PHP)
#0 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'D:\\xammp\\htdocs...', 35, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 10:05:28 --> Use of undefined constant d - assumed 'd' (this will throw an Error in a future version of PHP)
#0 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'D:\\xammp\\htdocs...', 35, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-02-15 10:05:41 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:05:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('fmbra@qivs.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'fmbra@qivs.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 10:07:57 --> syntax error, unexpected '}', expecting ')'
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:08:00 --> syntax error, unexpected '}', expecting ')'
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:08:01 --> syntax error, unexpected '}', expecting ')'
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:08:02 --> syntax error, unexpected '}', expecting ')'
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:08:15 --> syntax error, unexpected '}', expecting ')'
#0 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\xammp\\htdocs...')
#1 D:\xammp\htdocs\ci4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-15 10:08:41 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:08:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('pe2yx@lrtt.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'pe2yx@lrtt.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:09:45 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:09:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('pe2yx@lrtt.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'pe2yx@lrtt.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:11:49 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:11:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('x3jks@n7h8.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'x3jks@n7h8.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:13:00 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:13:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('x3jks@n7h8.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'x3jks@n7h8.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:13:15 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:13:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('m.adnan6425@gma...', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'm.adnan6425@gma...', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:13:46 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:13:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('m.adnan6425@gma...', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'm.adnan6425@gma...', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:14:01 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:14:01 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('tatt0@gz9j.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'tatt0@gz9j.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-02-15 10:19:26 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:19:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('tatt0@gz9j.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'tatt0@gz9j.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 10:19:30 --> Call to undefined function display_error()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(37): view('registration', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-15 10:19:56 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 10:19:56 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('aqzbd@rep1.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'aqzbd@rep1.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(34): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 10:20:27 --> Call to undefined function display_error()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(37): view('registration', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:22:49 --> syntax error, unexpected 'if' (T_IF)
#0 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration', Array, true)
#2 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(37): view('registration', Array)
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-15 10:22:51 --> syntax error, unexpected 'if' (T_IF)
#0 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#2 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(12): view('registration.ph...', Array)
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-15 10:22:54 --> syntax error, unexpected 'if' (T_IF)
#0 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#2 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(12): view('registration.ph...', Array)
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-15 10:25:24 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:25:28 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:25:31 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:25:32 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:26:08 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:26:14 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:26:49 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:27:16 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:27:38 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:27:41 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:28:25 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:28:28 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:29:26 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:29:28 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:35:17 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:35:22 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:35:25 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:35:28 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:36:12 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:44:40 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:44:42 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:44:55 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:45:25 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:45:31 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:45:37 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:46:31 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:46:46 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:46:49 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:49:18 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:49:23 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:50:47 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:50:54 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:50:56 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 10:54:11 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:55:41 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:56:24 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 10:59:19 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-15 11:00:25 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 11:00:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('uqg2f@jjui.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'uqg2f@jjui.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(35): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 11:01:30 --> Call to undefined function site_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 11:01:33 --> Call to undefined function site_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 11:02:59 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:03:02 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:03:08 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:04:58 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:05:05 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-02-15 11:05:27 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-02-15 11:05:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 D:\xammp\htdocs\ci4\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xammp\htdocs\ci4\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 D:\xammp\htdocs\ci4\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xammp\htdocs\ci4\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('8grvq@x9l3.com', 'cust_email', Array, NULL)
#4 D:\xammp\htdocs\ci4\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', '8grvq@x9l3.com', Array, Array)
#5 D:\xammp\htdocs\ci4\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(35): CodeIgniter\Controller->validate(Array)
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#9 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-02-15 11:24:51 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:25:06 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:25:15 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:31:00 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:33:03 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:35:43 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:37:28 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:38:08 --> Undefined variable: validation
#0 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(23): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'D:\\xammp\\htdocs...', 23, Array)
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#3 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-02-15 11:41:42 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:41:49 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:42:02 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:42:08 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:42:38 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:43:08 --> Call to undefined function App\Controllers\validate()
#0 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->registerCustomer()
#1 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#2 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-02-15 11:43:16 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(9): view('login.php')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:44:10 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(13): view('login.php', Array)
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:44:22 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(13): view('login.php', Array)
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:46:21 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Home.php(13): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Home->loginView()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:46:34 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Home.php(13): view('login')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Home->loginView()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 11:51:00 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Home.php(13): view('login.php')
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Home->loginView()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 12:06:48 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(13): view('login.php', Array)
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 12:06:56 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:07:06 --> include(include/head.php): failed to open stream: No such file or directory
#0 D:\xammp\htdocs\ci4\app\Views\login.php(2): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(include...', 'D:\\xammp\\htdocs...', 2, Array)
#1 D:\xammp\htdocs\ci4\app\Views\login.php(2): include()
#2 D:\xammp\htdocs\ci4\system\View\View.php(210): include('D:\\xammp\\htdocs...')
#3 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('login.php', Array, true)
#5 D:\xammp\htdocs\ci4\app\Controllers\Login.php(13): view('login.php', Array)
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Login->index()
#7 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-02-15 12:07:08 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:07:25 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:11:29 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:11:30 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration.ph...', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration.ph...', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:19:03 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-15 12:19:13 --> Call to undefined function set_value()
#0 D:\xammp\htdocs\ci4\system\View\View.php(210): include()
#1 D:\xammp\htdocs\ci4\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 D:\xammp\htdocs\ci4\system\Common.php(1089): CodeIgniter\View\View->render('registration', Array, true)
#3 D:\xammp\htdocs\ci4\app\Controllers\Registration.php(14): view('registration', Array)
#4 D:\xammp\htdocs\ci4\system\CodeIgniter.php(825): App\Controllers\Registration->index()
#5 D:\xammp\htdocs\ci4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Registration))
#6 D:\xammp\htdocs\ci4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xammp\htdocs\ci4\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
